Repository forus-labs/forui, pull requests merged in 2024-05, with the labels that each got.

#9 Prototype theme foundations
  forui/lib/forui.dart
  forui/lib/src/theme/font/font_data.dart
  forui/lib/src/theme/font/scaled_text_style.dart
  forui/lib/src/theme/style/zinc_style.dart
  forui/lib/src/theme/style_data.dart
  forui/lib/src/theme/theme.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/theme/widget_data.dart
  forui/lib/src/themes/zinc_theme.dart
  forui/lib/src/widgets/box/box.dart
  forui/lib/src/widgets/box/box_style.dart
  samples/lib/main.dart
Labels: difficulty: hard, duration: medium, priority: high, type: ehancement

#13 Support for material ancestry
  forui/lib/src/theme/font/font_data.dart
  forui/lib/src/theme/font/scaled_text_style.dart
  forui/lib/src/theme/theme.dart
  forui/pubspec.yaml
  samples/lib/main.dart
  samples/pubspec.yaml
Labels: difficulty: medium, duration: small, priority: high, type: ehancement

#15 Card widget
  forui/lib/forui.dart
  forui/lib/src/theme/widget_data.dart
  forui/lib/src/widgets/box/box.dart
  forui/lib/src/widgets/box/box_style.dart
  forui/lib/src/widgets/card/card.dart
  forui/lib/src/widgets/card/card_content.dart
  forui/lib/src/widgets/card/card_content_style.dart
  forui/lib/src/widgets/card/card_style.dart
  samples/ios/Runner.xcodeproj/project.pbxproj
  samples/lib/main.dart
  samples/pubspec.lock
Labels: difficulty: easy, duration: small, priority: medium, type: ehancement

#26 Fix separatorStyles throwing errors in console
  forui/example/lib/main.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/widgets/badge/badge.dart
  forui/lib/src/widgets/separator.dart
Labels: type: bug

#28 Font size
  .idea/runConfigurations/Update_Golden_Test_Images.xml
  forui/.gitignore
  forui/example/lib/main.dart
  forui/lib/src/theme/font.dart
  forui/lib/src/theme/theme.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/widgets/badge/badge.dart
  forui/lib/src/widgets/badge/badge_styles.dart
  forui/lib/src/widgets/card/card.dart
  forui/lib/src/widgets/card/card_content.dart
  forui/test/golden/card/zinc-dark-card-content.png
  forui/test/golden/card/zinc-light-card-content.png
  forui/test/src/theme/font_test.dart
Labels: difficulty: easy, duration: tiny, priority: medium
