Repository forus-labs/forui, pull requests merged in 2024-06, with the labels that each got.

#31 Add switch
  forui/example/pubspec.lock
  forui/lib/forui.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/widgets/switch.dart
  forui/test/golden/switch/zinc-dark-checked-disabled.png
  forui/test/golden/switch/zinc-dark-checked-focused.png
  forui/test/golden/switch/zinc-dark-checked-unfocused.png
  forui/test/golden/switch/zinc-dark-unchecked-disabled.png
  forui/test/golden/switch/zinc-dark-unchecked-focused.png
  forui/test/golden/switch/zinc-dark-unchecked-unfocused.png
  forui/test/golden/switch/zinc-light-checked-disabled.png
  forui/test/golden/switch/zinc-light-checked-focused.png
  forui/test/golden/switch/zinc-light-checked-unfocused.png
  forui/test/golden/switch/zinc-light-unchecked-disabled.png
  forui/test/golden/switch/zinc-light-unchecked-focused.png
  forui/test/golden/switch/zinc-light-unchecked-unfocused.png
  forui/test/src/widgets/switch_test.dart
Labels: difficulty: easy, duration: small, priority: low

#32 Docs foundations
  .idea/runConfigurations/dev.xml
  README.md
  docs/LICENSE
  docs/components/faq.mdx
  docs/components/logo.tsx
  docs/next.config.js
  docs/package.json
  docs/pages/_app.mdx
  docs/pages/docs/_meta.json
  docs/pages/docs/advanced.mdx
  docs/pages/docs/advanced/satori.mdx
  docs/pages/docs/card.mdx
  docs/pages/docs/themes.mdx
  docs/pages/docs/typography.mdx
  docs/pages/index.mdx
  docs/pnpm-lock.yaml
  docs/postcss.config.js
  docs/public/dark_logo.svg
  docs/public/favicon.ico
  docs/public/light_logo.svg
  docs/styles/globals.css
  docs/tailwind.config.js
  docs/theme.config.tsx
Labels: difficulty: medium, duration: small, priority: medium, type: ehancement

#30 Header
  .gitignore
  forui/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
  forui/example/android/local.properties
  forui/example/ios/Flutter/Generated.xcconfig
  forui/example/ios/Flutter/flutter_export_environment.sh
  forui/example/ios/Runner/GeneratedPluginRegistrant.h
  forui/example/ios/Runner/GeneratedPluginRegistrant.m
  forui/example/lib/main.dart
  forui/lib/forui.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/widgets/badge/badge.dart
  forui/lib/src/widgets/badge/badge_content.dart
  forui/lib/src/widgets/badge/badge_styles.dart
  forui/lib/src/widgets/button/button.dart
  forui/lib/src/widgets/button/button_content.dart
  forui/lib/src/widgets/button/button_content_style.dart
  forui/lib/src/widgets/button/button_style.dart
  forui/lib/src/widgets/button/button_styles.dart
  forui/lib/src/widgets/card/card.dart
  forui/lib/src/widgets/card/card_content.dart
  forui/lib/src/widgets/header/header.dart
  forui/lib/src/widgets/header/header_action.dart
  forui/test/golden/badge/zinc-dark-FBadgeVariant.destructive-badge-content.png
  forui/test/golden/badge/zinc-dark-FBadgeVariant.outline-badge-content.png
  forui/test/golden/badge/zinc-dark-FBadgeVariant.primary-badge-content.png
  forui/test/golden/badge/zinc-dark-FBadgeVariant.secondary-badge-content.png
  forui/test/golden/badge/zinc-light-FBadgeVariant.destructive-badge-content.png
  forui/test/golden/badge/zinc-light-FBadgeVariant.outline-badge-content.png
  forui/test/golden/badge/zinc-light-FBadgeVariant.primary-badge-content.png
  forui/test/golden/badge/zinc-light-FBadgeVariant.secondary-badge-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.destructive-disabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.destructive-enabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.outlined-disabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.outlined-enabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.primary-disabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.primary-enabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.secondary-disabled-button-content.png
  forui/test/golden/button/zinc-dark-FButtonVariant.secondary-enabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.destructive-disabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.destructive-enabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.outlined-disabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.outlined-enabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.primary-disabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.primary-enabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.secondary-disabled-button-content.png
  forui/test/golden/button/zinc-light-FButtonVariant.secondary-enabled-button-content.png
  forui/test/golden/card/zinc-dark-card-content.png
  forui/test/golden/card/zinc-light-card-content.png
  forui/test/golden/header/zinc-dark-header-actions.png
  forui/test/golden/header/zinc-dark-header-overflow.png
  forui/test/golden/header/zinc-dark-header.png
  forui/test/golden/header/zinc-light-header-actions.png
  forui/test/golden/header/zinc-light-header-overflow.png
  forui/test/golden/header/zinc-light-header.png
  forui/test/src/widgets/header_test.dart
Labels: difficulty: easy, duration: small, priority: medium, type: ehancement

#53 Scaffold
  .idea/runConfigurations/example___run.xml
  forui/example/lib/main.dart
  forui/lib/forui.dart
  forui/lib/src/theme/style.dart
  forui/lib/src/theme/theme_data.dart
  forui/lib/src/widgets/badge/badge_styles.dart
  forui/lib/src/widgets/header/header.dart
  forui/lib/src/widgets/scaffold.dart
  forui/test/golden/header/zinc-dark-header.png
  forui/test/golden/header/zinc-dark-raw-title.png
  forui/test/golden/header/zinc-light-header.png
  forui/test/golden/header/zinc-light-raw-title.png
  forui/test/golden/scaffold/zinc-dark.png
  forui/test/golden/scaffold/zinc-light.png
  forui/test/src/widgets/scaffold_golden_test.dart
Labels: difficulty: easy, duration: tiny, priority: low

#61 Solve issue with pub add instead of pub install (is not working)
  docs/pages/docs/index.mdx
Labels: type: bug
